using System;
using System.ComponentModel.DataAnnotations;

namespace LoanProcessing.Web.Models
{
    public class LoanApplication
    {
        public int ApplicationId { get; set; }

        // ApplicationNumber is generated by the database, not required from user
        [StringLength(20)]
        public string ApplicationNumber { get; set; }

        [Required(ErrorMessage = "Customer is required")]
        public int CustomerId { get; set; }

        [Required(ErrorMessage = "Loan type is required")]
        [StringLength(20)]
        public string LoanType { get; set; } // Personal, Auto, Mortgage, Business

        [Required(ErrorMessage = "Requested amount is required")]
        [Range(0.01, double.MaxValue, ErrorMessage = "Requested amount must be greater than zero")]
        public decimal RequestedAmount { get; set; }

        [Required(ErrorMessage = "Loan term is required")]
        [Range(12, 360, ErrorMessage = "Term must be between 12 and 360 months")]
        public int TermMonths { get; set; }

        [Required(ErrorMessage = "Purpose is required")]
        [StringLength(500)]
        public string Purpose { get; set; }

        // Status is set by the database, not required from user
        [StringLength(20)]
        public string Status { get; set; } // Pending, UnderReview, Approved, Rejected

        public DateTime ApplicationDate { get; set; }

        public decimal? ApprovedAmount { get; set; }

        public decimal? InterestRate { get; set; }

        // Navigation properties
        public virtual Customer Customer { get; set; }
    }
}
